# Generated by Django 5.2.3 on 2025-07-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_name_student_first_name_student_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ambulance_ID', models.CharField(max_length=55)),
                ('Driver_Name', models.CharField(max_length=50)),
                ('Driver_Phone_Number', models.IntegerField(max_length=10)),
                ('Vehicle_Number', models.CharField(max_length=25)),
                ('Ambulance_Type', models.CharField(max_length=100)),
                ('Driver_Password', models.CharField(max_length=15)),
            ],
        ),
    ]
