# Generated by Django 5.2.3 on 2025-07-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_student_options_alter_student_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='ambulance',
            name='Ambulance_Type',
            field=models.CharField(choices=[('Basic Life Support', 'Basic Life Support'), ('Advanced Life Support', 'Advanced Life Support'), ('ICU Ambulance', 'ICU Ambulance'), ('Oxygen Ambulance', 'Oxygen Ambulance')], max_length=100),
        ),
    ]
